services:
  bff:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: abcall-local-bff
    restart: always
    volumes:
      - ".:/app"
    ports:
      - "5002:3002"
    env_file:
      - .env.local
    tty: true
    links:
      - auth-api
      - customer-api
    depends_on:
      - auth-api
      - customer-api
    networks:
      - app_net
  auth-api:
    build:
      context: ../abcall-auth-api/.
      dockerfile: ../abcall-auth-api/dev.Dockerfile
    container_name: abcall-auth-api
    volumes:
      - "../abcall-auth-api/.:/app"
    env_file:
      - ../abcall-auth-api/.env.local
    environment:
      - DATABASE_URI=postgresql+psycopg2://develop:d3v3l0p@db:5432/abcall-db
    ports:
      - "5004:3004"
    tty: true
    links:
      - db
    depends_on:
      - db
    networks:
      - app_net
  customer-api:
    build:
      context: ../abcall-customer-api/.
      dockerfile: ../abcall-customer-api/dev.Dockerfile
    container_name: abcall-customer-api
    volumes:
      - "../abcall-customer-api/.:/app"
    env_file:
      - ../abcall-customer-api/.env.local
    environment:
      - DATABASE_URI=postgresql+psycopg2://develop:d3v3l0p@db:5432/abcall-db
    ports:
      - "5003:3003"
    tty: true
    links:
      - db
    depends_on:
      - db
    networks:
      - app_net
  
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    env_file:
      - .env.db
    container_name: local-db
    volumes:
      - "./data/postgresql:/var/lib/postgresql"
      - "./docker/postgresql:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    networks:
      - app_net

networks:
  app_net:
    name: app_net
    driver: bridge