version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: abcall-bff-api
    restart: always
    volumes:
      - ".:/app"
    ports:
      - "3002:3002"
    env_file:
      - .env
    tty: true