apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-configmap
data:
  FLASK_APP: "flaskr/app"
  FLASK_ENV: "production"
  APP_NAME: "abcall-bff"
  PAYMENT_API_PATH: "http://abcall-payment-api-service:3005"
  URL_REPORTS_SERVICE: "http://abcall-reports-api-service:3008"
  ISSUE_API_PATH: "http://abcall-issues-api-service:3007"